<a href="https://colab.research.google.com/github/ujin2021/ML_CrashCourse/blob/main/unit3_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy and Pandas

#### Numpy
* array를 간단하게 표현해주고, linear algebra opration을 수행함.

In [ ]:
import numpy as np

In [ ]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5]) # list가 아닌 array
print(one_dimensional_array) # 쉼표가 없다

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [ ]:
two_diensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_diensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
zero_array = np.zeros(6)
print(zero_array)
one_array = np.ones(6)
print(one_array)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [ ]:
# np.arange
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers) # 5이상, 12미만

[ 5  6  7  8  9 10 11]


In [ ]:
# np.random.randint (low이상, high 미만)
random_integers_between_50_and_100 = np.random.randint(low = 50, high = 101, size = (6))
print(random_integers_between_50_and_100)

# np.random.random (0과 1 사이의 float)
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[ 62  61  86 100  79  80]
[0.99664402 0.84050151 0.23523233 0.31156894 0.70839692 0.94461608]


In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

random_integers_between_150_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_300)

[2.99664402 2.84050151 2.23523233 2.31156894 2.70839692 2.94461608]
[186 183 258 300 237 240]


In [ ]:
# Create a Linear Dataset
# create a simpole dataset consisting of a single feature and a label
# label = (3)(feature) + 4. if feature = 6, label = 22

# 1. Assign a sequence of integers from 6 to 20
feature = np.arange(6, 21)
print(feature)
# 2. Assign 15 values to a NumPy array named label
label = (feature * 3) + 4 # feature가 array인데, 바로 연산을 하면 결과도 array
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
# Make dataset a little more realistic
# insert a little random noise(float, -2 to 2)

noise = (np.random.random([15]) * 4) - 2 # 위에서 6 ~ 20까지니까 array크기는 15
# np.random.random : 0 to 1, np.random.random * 4 - 2 : -2 to 2
print(noise)

label = label + noise
print(label)

[-0.73876507  0.30972912 -0.60738342  0.98307206 -1.04055646  1.37608712
  1.94052099 -0.66195136  0.77891494  0.03749328  1.79021784  0.42234237
 -0.84865655  0.32176692  1.55695849]
[21.26123493 25.30972912 27.39261658 31.98307206 32.95944354 38.37608712
 41.94052099 42.33804864 46.77891494 49.03749328 53.79021784 55.42234237
 57.15134345 61.32176692 65.55695849]


#### Pandas
* memory의 dataset을 간단하게 표현해줌.

In [ ]:
import pandas as pd

In [ ]:
# Create and populate a 5x2 Numpy array
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two colums
my_column_names = ['temperature', 'activity']

# Create a DataFrame
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [ ]:
# Create a new column
my_dataframe["adjusted"] = my_dataframe["activity"] + 2
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [ ]:
# Subset of Dataframe(indexing, slicing)
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n') # iloc : 위치기반 indexing

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column temperature")
print(my_dataframe['temperature'])

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 

Row #2:
   temperature  activity  adjusted
2           20         9        11 

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 

Column temperature
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64


In [ ]:
my_data = np.random.randint(low=0, high=101, size=(3, 4)) # size에 2차원 배열도 가능..!!
my_data_columns = ['Eleanor', 'Chidi', 'Tahani', 'Jason']
my_dataframe = pd.DataFrame(data=my_data, columns=my_data_columns)

print(my_dataframe)
print(my_dataframe['Eleanor'][1])

my_dataframe['Janet'] = my_dataframe['Tahani'] + my_dataframe['Jason']
print(my_dataframe)

   Eleanor  Chidi  Tahani  Jason
0       61     87      38     58
1       43     17      19     37
2       99     91      64     77
43
   Eleanor  Chidi  Tahani  Jason  Janet
0       61     87      38     58     96
1       43     17      19     37     56
2       99     91      64     77    141


In [ ]:
# Copying a Dataframe
# Referencing : original이 변경되면 refence하는 dataframe도 변경됨
# Copying : pd.DataFrame.copy : original이 변경돼도 refence하는 dataframe도 변경안됨(독립적)

print('Reference')
reference_to_df = my_dataframe
print(f"reference_to_df['Jason'][1] = {reference_to_df['Jason'][1]}, my_dataframe['Jason'][1] = {my_dataframe['Jason'][1]}")

my_dataframe['Jason'][1] = 3

print(f"reference_to_df['Jason'][1] = {reference_to_df['Jason'][1]}, my_dataframe['Jason'][1] = {my_dataframe['Jason'][1]}")

print('\nCopy')
copy_of_df = my_dataframe.copy()
print(f"copy_of_df['Jason'][1] = {copy_of_df['Jason'][1]}, my_dataframe['Jason'][1] = {my_dataframe['Jason'][1]}")

my_dataframe['Jason'][1] = 6

print(f"copy_of_df['Jason'][1] = {copy_of_df['Jason'][1]}, my_dataframe['Jason'][1] = {my_dataframe['Jason'][1]}")

Reference
reference_to_df['Jason'][1] = 3, my_dataframe['Jason'][1] = 3
reference_to_df['Jason'][1] = 3, my_dataframe['Jason'][1] = 3

Copy
copy_of_df['Jason'][1] = 3, my_dataframe['Jason'][1] = 3
copy_of_df['Jason'][1] = 3, my_dataframe['Jason'][1] = 6
